name: Update Data Weekly

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python 3.11
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      - name: Run ETL script
        run: python ETL_Football_pipeline.py  # Execute your ETL script
