name: Update Data Weekly

on:
  schedule:
    - cron: '0 0 * * 0'  # This schedules the job to run every Sunday at midnight UTC

jobs:
  update-data:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Check out your repository so that the runner can access it

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install any Python packages your script needs

    - name: Run ETL script
      run: |
        python ETL_Football_pipeline.py  # Run your ETL script
